[Paths]
# 默认输入文件目录
input_directory = ./input
# 默认输出文件目录
output_directory = ./output

[Defaults]
# 当源文件格式是 docx 时，默认的目标格式
default_docx_to_format = pdf
# 你可以根据需要添加更多默认转换规则，例如：
default_pdf_to_format = docx
default_xlsx_to_format = csv
default_md_to_format = docx
default_html_to_format = md


[Conversion]
default_format = pdf
overwrite = false
pdf_engine = weasyprint

[Log]
log_dir = ./logs
